server:
  port: 8099

spring:
  application:
    name:  producer-api
  webflux:
    base-path: /producer-api
  cloud:
    stream:
      bindings:
        iot-data:
          destination: log-data
          group: output-group-1
          content-type: application/json
      kafka:
        binder:
          brokers:
            - localhost:9092
          producer-properties:
            client.id: producer-api
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    root: INFO


management:
  endpoints:
    web:
      base-path: /
